from pathlib import Path

# 1) Preserve the historical protocol-complete denial contract for sibling calls.
p = Path("src/runtime/runtimeTurnToolBatch.ts")
s = p.read_text()
old = '''      error: {\n        code: "booking_batch_aborted",\n        message: "Tool was not executed because the batch contained a conflicting booking write request",\n      },'''
new = '''      error: {\n        code: "turn_aborted_due_to_multiple_booking_requests",\n        message: "turn_aborted_due_to_multiple_booking_requests",\n      },'''
if s.count(old) != 1:
    raise SystemExit(f"runtimeTurnToolBatch sibling denial expected once, found {s.count(old)}")
s = s.replace(old, new, 1)
p.write_text(s)

# 2) R3i ownership now follows loop -> complete turn batch -> preparation boundary.
p = Path("tests/r3iBookingApplyExecutionPreparation.test.ts")
s = p.read_text()
old = '''test("R3i structure: legacy loop delegates booking target plumbing to one preparation boundary", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSource = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n\n  assert.match(loopSource, /from\\s+["']\\.\\/bookingApplyExecutionPreparation\\.ts["']/);\n  assert.equal(\n    loopSource.match(/prepareBookingApplyExecution\\(\\{/g)?.length,\n    2,\n    "both current tool-batch paths must share the same preparation boundary",\n  );\n  assert.doesNotMatch(loopSource, /from\\s+["']\\.\\/bookingSubjectExecutionResolver\\.ts["']/);\n  assert.doesNotMatch(loopSource, /bootstrapRegistryFromBookingApplyArgs/);\n  assert.doesNotMatch(loopSource, /parseSubjectTarget/);\n  assert.doesNotMatch(loopSource, /resolveBookingExecutionSubject/);\n});'''
new = '''test("R3u structure: complete turn-batch owner delegates booking target plumbing to one preparation boundary", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSource = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n  const batchSource = await readFile(resolve(thisDir, "../src/runtime/runtimeTurnToolBatch.ts"), "utf8");\n\n  assert.match(loopSource, /from\\s+["']\\.\\/runtimeTurnToolBatch\\.ts["']/);\n  assert.equal(\n    loopSource.match(/executeRuntimeTurnToolBatch\\(\\{/g)?.length,\n    2,\n    "both current model tool batches must share the complete turn-batch owner",\n  );\n  assert.doesNotMatch(loopSource, /bookingApplyExecutionPreparation\\.ts/);\n  assert.doesNotMatch(loopSource, /prepareBookingApplyExecution\\(/);\n  assert.match(batchSource, /from\\s+["']\\.\\/bookingApplyExecutionPreparation\\.ts["']/);\n  assert.equal(\n    batchSource.match(/prepareBookingApplyExecution\\(\\{/g)?.length,\n    1,\n    "complete turn-batch owner must prepare the booking target through one boundary",\n  );\n  assert.doesNotMatch(loopSource, /from\\s+["']\\.\\/bookingSubjectExecutionResolver\\.ts["']/);\n  assert.doesNotMatch(loopSource, /bootstrapRegistryFromBookingApplyArgs/);\n  assert.doesNotMatch(loopSource, /parseSubjectTarget/);\n  assert.doesNotMatch(loopSource, /resolveBookingExecutionSubject/);\n});'''
if s.count(old) != 1:
    raise SystemExit(f"R3i structure block expected once, found {s.count(old)}")
s = s.replace(old, new, 1)
p.write_text(s)

# 3) R3l ownership now follows loop -> complete turn batch -> canonical request execution.
p = Path("tests/r3lRuntimeToolRequestExecution.test.ts")
s = p.read_text()
old = '''test("R3l structure: legacy loop no longer owns policy-backed execution plumbing", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSource = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n\n  assert.equal(\n    loopSource.match(/executeRuntimeToolRequest\\(\\{/g)?.length,\n    2,\n    "first normal path and later booking.apply path must share one execution pipeline",\n  );\n  assert.match(loopSource, /export \\{ buildSubjectAwarePhoneFields, hasSubjectOrContactPhone \\} from ["']\\.\\/runtimeToolRequestExecution\\.ts["']/);\n  assert.doesNotMatch(loopSource, /applyToolPolicy\\(/);\n  assert.doesNotMatch(loopSource, /executeAllowedTools\\(/);\n  assert.doesNotMatch(loopSource, /buildTruthSnapshot\\(/);\n  assert.doesNotMatch(loopSource, /buildPlannerFromAgentToolRequest\\(/);\n  assert.doesNotMatch(loopSource, /resolveTruthSnapshot\\(/);\n  assert.doesNotMatch(loopSource, /buildExecutionContext\\(/);\n  assert.doesNotMatch(loopSource, /convertToolExecutionResult\\(/);\n});'''
new = '''test("R3u structure: complete turn-batch owner contains policy-backed write execution plumbing", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSource = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n  const batchSource = await readFile(resolve(thisDir, "../src/runtime/runtimeTurnToolBatch.ts"), "utf8");\n\n  assert.equal(\n    loopSource.match(/executeRuntimeTurnToolBatch\\(\\{/g)?.length,\n    2,\n    "first and later model tool batches must share one complete turn-batch owner",\n  );\n  assert.doesNotMatch(loopSource, /executeRuntimeToolRequest\\(/);\n  assert.match(batchSource, /from ["']\\.\\/runtimeToolRequestExecution\\.ts["']/);\n  assert.equal(\n    batchSource.match(/executeRuntimeToolRequest\\(\\{/g)?.length,\n    1,\n    "complete turn-batch owner must use the canonical request execution pipeline for the booking write",\n  );\n  assert.match(loopSource, /export \\{ buildSubjectAwarePhoneFields, hasSubjectOrContactPhone \\} from ["']\\.\\/runtimeToolRequestExecution\\.ts["']/);\n  assert.doesNotMatch(loopSource, /applyToolPolicy\\(/);\n  assert.doesNotMatch(loopSource, /executeAllowedTools\\(/);\n  assert.doesNotMatch(loopSource, /buildTruthSnapshot\\(/);\n  assert.doesNotMatch(loopSource, /buildPlannerFromAgentToolRequest\\(/);\n  assert.doesNotMatch(loopSource, /resolveTruthSnapshot\\(/);\n  assert.doesNotMatch(loopSource, /buildExecutionContext\\(/);\n  assert.doesNotMatch(loopSource, /convertToolExecutionResult\\(/);\n});'''
if s.count(old) != 1:
    raise SystemExit(f"R3l structure block expected once, found {s.count(old)}")
s = s.replace(old, new, 1)
p.write_text(s)
