from pathlib import Path

# 1) Booking apply truth ownership moved from legacy shell to roundless model projection.
p = Path("tests/bookingApplyActivation.test.ts")
s = p.read_text()
old = '''// ── Proof: booking_apply_action_truth is passed to model in legacy Runtime implementation ──\n\ntest("proof: runtimeAgentLoopLegacy.ts injects booking_apply_action_truth into second model call context", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSrc = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n  assert.match(loopSrc, /booking_apply_action_truth/, "runtimeAgentLoopLegacy must inject booking_apply_action_truth into model context");\n  assert.match(loopSrc, /buildBookingApplyActionTruth/, "runtimeAgentLoopLegacy must call buildBookingApplyActionTruth");\n});\n'''
new = '''// ── Proof: booking_apply_action_truth is projected through the roundless model-context owner ──\n\ntest("proof: roundless model projection injects booking_apply_action_truth into model context", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSrc = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n  const projectionSrc = await readFile(resolve(thisDir, "../src/runtime/runtimeTurnModelContext.ts"), "utf8");\n  assert.doesNotMatch(loopSrc, /buildBookingApplyActionTruth/, "legacy shell must not own booking truth projection");\n  assert.match(projectionSrc, /buildBookingApplyActionTruth\(params\.tool_results\)/, "roundless projection must build booking_apply_action_truth from accumulated tool results");\n  assert.match(projectionSrc, /booking_apply_action_truth:\s*bookingApplyTruth/, "roundless projection must inject booking_apply_action_truth into model context");\n});\n'''
if s.count(old) != 1:
    raise SystemExit(f"bookingApplyActivation structural block count={s.count(old)}")
s = s.replace(old, new, 1)
p.write_text(s)

# 2) R3t/R3v ownership test no longer relies on the deleted terminal-helper marker.
p = Path("tests/r3tRuntimeModelIteration.test.ts")
s = p.read_text()
old = '''test("R3v structure: the main runTurn shell delegates one bounded iteration transport state to the iterator", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSource = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n  const iteratorSource = await readFile(resolve(thisDir, "../src/runtime/runtimeBoundedModelToolLoop.ts"), "utf8");\n  const helperBoundary = loopSource.indexOf("// ── Multiple-blocked booking.apply helper");\n  assert.ok(helperBoundary > 0);\n  const runTurnSource = loopSource.slice(0, helperBoundary);\n\n  assert.match(runTurnSource, /createRuntimeModelIterationState\\(conversationId\\)/);\n  assert.equal(runTurnSource.match(/runRuntimeTurnModelToolOrchestration\\(\\{/g)?.length, 1);\n  assert.equal(\n    runTurnSource.match(/invokeRuntimeModelIteration\\(\\{/g)?.length ?? 0,\n    0,\n    "legacy shell must not own numbered model steps anymore",\n  );\n  assert.equal(\n    iteratorSource.match(/invokeRuntimeModelIteration\\(\\{/g)?.length,\n    1,\n    "generic iterator must be the single owner of bounded model-call progression",\n  );\n  assert.doesNotMatch(\n    runTurnSource,\n    /invokeRuntimeModelCall\\(\\{/,\n    "main runTurn path must not bypass bounded iteration transport",\n  );\n});'''
new = '''test("R3w structure: the legacy shell delegates one bounded iteration transport state to the iterator", async () => {\n  const thisDir = dirname(fileURLToPath(import.meta.url));\n  const loopSource = await readFile(resolve(thisDir, "../src/runtime/runtimeAgentLoopLegacy.ts"), "utf8");\n  const iteratorSource = await readFile(resolve(thisDir, "../src/runtime/runtimeBoundedModelToolLoop.ts"), "utf8");\n\n  assert.match(loopSource, /createRuntimeModelIterationState\\(conversationId\\)/);\n  assert.equal(loopSource.match(/runRuntimeTurnModelToolOrchestration\\(\\{/g)?.length, 1);\n  assert.equal(\n    loopSource.match(/invokeRuntimeModelIteration\\(\\{/g)?.length ?? 0,\n    0,\n    "legacy shell must not own numbered model steps anymore",\n  );\n  assert.equal(\n    iteratorSource.match(/invokeRuntimeModelIteration\\(\\{/g)?.length,\n    1,\n    "generic iterator must be the single owner of bounded model-call progression",\n  );\n  assert.doesNotMatch(\n    loopSource,\n    /invokeRuntimeModelCall\\(\\{/,\n    "legacy shell must not bypass bounded iteration transport",\n  );\n  assert.doesNotMatch(loopSource, /finalizeBlockedMultipleBookingApplies|finalizeBlockedBookingApplyWithToolOutput/);\n});'''
if s.count(old) != 1:
    raise SystemExit(f"r3t structural block count={s.count(old)}")
s = s.replace(old, new, 1)
p.write_text(s)
