from pathlib import Path

agent_path = Path("src/runtime/openaiRuntimeAgent.ts")
workflow_path = Path(".github/workflows/runtime-tests.yml")
script_path = Path(__file__)

agent = agent_path.read_text()
old = '''    // ── BOOKING PEOPLE ────────────────────────────────────────────────────────\n    "## BOOKING PEOPLE",\n    "Treat people by business meaning. Never use or emit internal subject identifiers.",\n    "runtime_context.booking_subjects.subjects exposes human label/name plus person_kind and is_active. Use those fields to identify the intended person.",\n    "Include subject_intent in final_response only when switching person or creating another person.",\n    `subject_intent: {action:"none"|"switch_subject"|"create_subjects", target:"self"|"active"|"other_person", person_ref:null|string, display_name:null|string, count:null|1..4, labels:[], confidence:"low"|"medium"|"high"}`,\n    "For other_person, set person_ref to the exact visible label or patient_name when more than one other person exists. If the person is ambiguous, ask which person and do not guess.",\n    "When pending_typed_phone is set, ask whose phone it is and include phone_ownership_intent in final_response.",\n    `phone_ownership_intent: {action:"assign_pending_phone"|"share_sender_contact"|"none", target:"self"|"active"|"other_person", person_ref:null|string, confidence:"low"|"medium"|"high"}`,\n    "Never emit subject_id, target_subject_id, subject_1, subject_2, subject_3, or subject_4.",\n'''
new = '''    // ── BOOKING PEOPLE ────────────────────────────────────────────────────────\n    "## BOOKING PEOPLE",\n    "Identify via runtime_context.booking_subjects.subjects label/name, person_kind and is_active.",\n    `On switch/create: subject_intent:{action:"none"|"switch_subject"|"create_subjects",target:"self"|"active"|"other_person",person_ref:null|string,display_name:null|string,count:null|1..4,labels:[],confidence:"low"|"medium"|"high"}.`,\n    "Multiple other_person: person_ref must exactly match visible label/patient_name; if ambiguous, ask.",\n    `pending_typed_phone: ask owner; return phone_ownership_intent:{action:"assign_pending_phone"|"share_sender_contact"|"none",target:"self"|"active"|"other_person",person_ref:null|string,confidence:"low"|"medium"|"high"}.`,\n    "Never emit subject_id, target_subject_id or subject_1..4.",\n'''
if old not in agent:
    raise SystemExit("R3g people block not found")
agent_path.write_text(agent.replace(old, new, 1))

workflow_path.write_text('''name: Runtime tests\n\non:\n  pull_request:\n  push:\n    branches:\n      - ai-dental-frontdesk-core\n  workflow_dispatch:\n\npermissions:\n  contents: read\n\nconcurrency:\n  group: runtime-tests-${{ github.workflow }}-${{ github.ref }}\n  cancel-in-progress: true\n\njobs:\n  test:\n    name: npm test\n    runs-on: ubuntu-latest\n    timeout-minutes: 15\n\n    steps:\n      - name: Checkout\n        uses: actions/checkout@v4\n\n      - name: Setup Node.js\n        uses: actions/setup-node@v4\n        with:\n          node-version: 22\n          cache: npm\n\n      - name: Install dependencies\n        run: npm ci\n\n      - name: Run full test suite\n        shell: bash\n        run: |\n          set -o pipefail\n          npm test 2>&1 | tee test-output.txt\n\n      - name: Upload test output\n        if: always()\n        uses: actions/upload-artifact@v4\n        with:\n          name: runtime-test-output\n          path: test-output.txt\n          if-no-files-found: error\n''')
script_path.unlink()
print("R3g prompt shrunk; workflow restored; script removed")
